language: java
os:
  - osx
  - linux
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gradle  ; fi

install:
  - DIR=$PWD; (cd /tmp; gradle wrapper --gradle-version=5.2.1; mv .gradle gradle gradlew $DIR)

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew packageApplicationDmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew build ; fi
  - ls -l build/distributions/*
  - test -f build/distributions/OMERO.imagej-*
  - test -f build/distributions/OMERO.insight-*

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true
